import SwiftJavaConfigurationShared

// MARK: - Kotlin source writing

extension KotlinSwift2KotlinGenerator {

  /// Write Kotlin sources to disk.
  package func writeKotlinSources() throws {
    var printer = CodePrinter(mode: .flushToFileOnWrite)
    try writeKotlinSources(&printer)
  }

  /// Write Kotlin sources into the given printer (used by tests with `.accumulateAll` mode).
  package func writeKotlinSources(_ printer: inout CodePrinter) throws {
    printHeader(&printer)
    printPackage(&printer)
    printer.println()

    for decl in analysis.importedGlobalFuncs {
      guard decl.apiKind == .function else { continue }
      printGlobalFunction(&printer, decl)
    }

    let kotlinPackagePath = kotlinPackage.isEmpty ? nil : kotlinPackage.replacingOccurrences(of: ".", with: "/")
    _ = try printer.writeContents(
      outputDirectory: outputKotlinDirectory,
      javaPackagePath: kotlinPackagePath,
      filename: "\(swiftModuleName).kt"
    )
  }
}

// MARK: - Printing helpers

extension KotlinSwift2KotlinGenerator {

  private func printHeader(_ printer: inout CodePrinter) {
    printer.print("// Generated by jextract-swift")
    printer.print("// Swift module: \(swiftModuleName)")
  }

  private func printPackage(_ printer: inout CodePrinter) {
    guard !kotlinPackage.isEmpty else { return }
    printer.println()
    printer.print("package \(kotlinPackage)")
  }

  /// Print a single top-level Kotlin function declaration with a TODO stub body.
  private func printGlobalFunction(_ printer: inout CodePrinter, _ decl: ImportedFunc) {
    let sig = decl.functionSignature

    // Map return type
    let kotlinReturnType: String
    if sig.result.type.isVoid {
      kotlinReturnType = "Unit"
    } else if let mapped = swiftTypeToKotlinType(sig.result.type) {
      kotlinReturnType = mapped
    } else {
      logger.debug("Skipping \(decl.name): unsupported return type")
      return
    }

    // Map parameters — skip the whole function if any param type is unsupported
    var kotlinParams: [String] = []
    for param in sig.parameters {
      guard let kotlinType = swiftTypeToKotlinType(param.type) else {
        logger.debug("Skipping \(decl.name): unsupported parameter type")
        return
      }
      let paramName = param.parameterName ?? param.argumentLabel ?? "_"
      kotlinParams.append("\(paramName): \(kotlinType)")
    }

    let paramsString = kotlinParams.joined(separator: ", ")

    printer.printBraceBlock("fun \(decl.name)(\(paramsString)): \(kotlinReturnType)") { printer in
      printer.print("TODO(\"Not implemented\")")
    }
    printer.println()
  }
}
