//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2025 Apple Inc. and the Swift.org project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Swift.org project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import JExtractSwiftLib
import Testing

@Suite
struct KotlinGlobalFunctionTests {

  @Test
  func emitsHeaderAndPackage() throws {
    let input = "public func helloWorld()"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        // Generated by jextract-swift
        // Swift module: SwiftModule
        """,
        """
        package com.example.swift
        """,
      ]
    )
  }

  @Test
  func simpleVoidFunction() throws {
    let input = "public func helloWorld()"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun helloWorld(): Unit {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithIntParameter() throws {
    let input = "public func takeInt(i: Int)"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun takeInt(i: Long): Unit {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithInt32Parameter() throws {
    let input = "public func takeInt32(i: Int32)"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun takeInt32(i: Int): Unit {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithReturnType() throws {
    let input = "public func makeDouble() -> Double"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun makeDouble(): Double {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithMultipleParamsAndReturn() throws {
    let input = "public func compute(a: Int32, b: Bool) -> Double"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun compute(a: Int, b: Boolean): Double {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithStringTypes() throws {
    let input = "public func copy(_ string: String) -> String"

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun copy(string: String): String {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func functionWithPrimitives() throws {
    let input = """
      public func helloWorld()
      public func takeIntegers(i1: Int8, i2: Int16, i3: Int32, i4: Int64)
      public func otherPrimitives(b: Bool, f: Float, d: Double)
      """

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun helloWorld(): Unit {
          TODO("Not implemented")
        }
        """,
        """
        fun takeIntegers(i1: Byte, i2: Short, i3: Int, i4: Long): Unit {
          TODO("Not implemented")
        }
        """,
        """
        fun otherPrimitives(b: Boolean, f: Float, d: Double): Unit {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }

  @Test
  func multipleFunctions() throws {
    let input = """
      public func first(a: Int32) -> Bool
      public func second(name: String) -> String
      """

    try assertKotlinOutput(
      input: input,
      expectedChunks: [
        """
        fun first(a: Int): Boolean {
          TODO("Not implemented")
        }
        """,
        """
        fun second(name: String): String {
          TODO("Not implemented")
        }
        """,
      ]
    )
  }
}
